apiVersion: apps/v1
kind: Deployment
metadata:
  name: survivordetv2
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx:latest
        ports:
        - containerPort: 8080
